// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
// import { cn } from "@/lib/utils";
// import Header from "./components/Header";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className="dark">
//       <body className={cn(inter.className, "dark:bg-black dark:text-white")}>
//         <Header />
//         {children}</body>
//     </html>
//   );
// }

// import Image from "next/image";
// import HeroSection from "./components/HeroSection";
// import LatestQuestions from "./components/LatestQuestions";
// import TopContributers from "./components/TopContributors";

// export default function Home() {
//   return (
//     <main className="flex min-h-screen flex-col items-center justify-between p-24 my-6">
//       <HeroSection/>
//       <LatestQuestions/>
//       <TopContributers/>
//     </main>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";
import Header from "./components/Header";
import Footer from "./components/Footer";
export const metadata: Metadata = {
  title: "CodeCell",
  description: "Generated By Ansh Jain",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn(inter.className, "dark:bg-black dark:text-white")}>
        <Header />
        {children}
        <Footer/>
        </body>
    </html>
  );
}